#!/usr/bin/env python

import sys
import os
import time

str_file = sys.argv[1]

f = open(str_file, "r")
linhas = f.readlines()

print linhas
param = {}

for x in range(len(linhas)):
	if x==0: continue
	chave, valor = linhas[x].split("=", 1)
	chave = chave.strip()
	valor = valor.strip()
	print chave, ":", valor,
	param[chave] = valor
	if chave=="ca":
		ca = open("ca.temp", "w")
		ca_linhas = valor.replace("\\n", "\n")
		ca.write(ca_linhas)
		ca.close()

f.close()

comando = "spicec --host %s --port %s --secure-port %s --ca-file %s --password '%s' --title '%s' --tls-ciphers %s --host-subject '%s'" % (param["host"], param["port"], param["tls-port"], "ca.temp", param["password"], param["title"], param["tls-ciphers"], param["host-subject"])

print
print
print comando
print

os.system(comando)

exit(0)
